import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  container: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 96,
    gap: 20,
  },
  header: {
    borderBottomWidth: 0,
    paddingBottom: 16,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#0f172a",
  },
  subtitle: {
    marginTop: 6,
    color: "#64748b",
    fontSize: 15,
    fontWeight: "500",
  },
  card: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    padding: 16,
    backgroundColor: "#ffffff",
    gap: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#0ea5e9",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#0ea5e9",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  avatarText: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "800",
  },
  profileName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
  },
  sectionTitle: {
    marginBottom: 10,
    marginLeft: 4,
    fontSize: 14,
    fontWeight: "800",
    color: "#0f172a",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 4,
    paddingVertical: 10,
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 1,
  },
  rowTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  rowSubtitle: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "500",
  },
  divide: {
    gap: 0,
    paddingHorizontal: 0,
  },
  linkRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e2e8f0",
  },
  sectionSpacing: {
    paddingTop: 12,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    fontSize: 11,
    overflow: "hidden",
    fontWeight: "700",
  },
  badgeOutline: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    color: "#0f172a",
    backgroundColor: "#f8fafc",
  },
  badgeSolid: {
    backgroundColor: "#cffafe",
    color: "#0c4a6e",
  },
  progressTrack: {
    height: 8,
    borderRadius: 8,
    backgroundColor: "#e2e8f0",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#0ea5e9",
  },
  button: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimary: {
    backgroundColor: "#0ea5e9",
  },
  buttonPrimaryText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
  buttonOutline: {
    borderWidth: 2,
    borderColor: "#0ea5e9",
    marginTop: 8,
    backgroundColor: "#f8fafc",
  },
  buttonOutlineText: {
    color: "#0369a1",
    fontWeight: "800",
    fontSize: 15,
  },
  buttonGhost: {
    borderWidth: 1,
    borderColor: "#fecaca",
    backgroundColor: "#fef2f2",
  },
  buttonGhostText: {
    color: "#991b1b",
    fontWeight: "800",
    fontSize: 15,
  },
  buttonText: {
    fontSize: 15,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoLabel: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "500",
  },
  systemInfo: {
    backgroundColor: "#f8fafc",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
  },
  input: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 15,
    color: "#0f172a",
    backgroundColor: "#ffffff",
  },
  settingToggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e2e8f0",
    gap: 12,
  },
  circleIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#dbeafe",
    alignItems: "center",
    justifyContent: "center",
  },
  circleIconText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0369a1",
  },
});

export default styles;
